# Step 1: Use Ubuntu 22.04 as the base image
FROM ubuntu:22.04

# Set environment variables
ENV RC_VERSION=3.16.2 HOME=/app TERM=xterm METEOR_ALLOW_SUPERUSER=true

# Set working directory
WORKDIR /app

# Install dependencies and Node.js
RUN groupadd -r rocketchat && useradd -r -g rocketchat rocketchat \
    && apt-get update && apt-get install -y --no-install-recommends \
    xz-utils openssl libssl-dev ca-certificates curl fontconfig git make openssh-server python3 vim \
    ## Cypress dependencies
    libgtk2.0-0 libgtk-3-0 libgbm-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb \
    && apt-get install -y --no-install-recommends libnotify-dev g++ build-essential \
    && rm -rf /var/lib/apt/lists/* \
    && curl -fsSL https://nodejs.org/dist/v14.21.3/node-v14.21.3-linux-x64.tar.xz -o node-v14.21.3-linux-x64.tar.xz \
    && tar -xJf node-v14.21.3-linux-x64.tar.xz \
    && mv node-v14.21.3-linux-x64 /usr/local/nodejs \
    && ln -s /usr/local/nodejs/bin/node /usr/local/bin/node \
    && ln -s /usr/local/nodejs/bin/npm /usr/local/bin/npm

# Ensure proper permissions
RUN mkdir -p /app/.cache/node-gyp \
    && chown -R rocketchat:rocketchat /app

# Install Meteor and Rocket.Chat
USER rocketchat
RUN curl https://install.meteor.com/?release=2.16 | sh \
    && git clone --branch joe-test https://github.com/hmchangw/Rocket.Chat /app/Rocket.Chat

# Add Meteor to PATH or copy the binary to a global location
USER root
RUN echo 'export PATH="$HOME/.meteor:$PATH"' >> /etc/profile.d/meteor.sh \
    && chmod +x /etc/profile.d/meteor.sh \
    && ln -s /app/.meteor/meteor /usr/bin/meteor

# Install Node.js dependencies
USER root
RUN cd /app/Rocket.Chat \
    && meteor npm install \
    && cd /app/Rocket.Chat/ee/server/services \
    && meteor npm install && cd - \
    && echo 'pcm.!default {\n type hw\n card 0\n}\n\nctl.!default {\n type hw\n card 0\n}' > /app/.asoundrc

RUN cd /app/Rocket.Chat && \
    (TEST_MODE=true meteor run & sleep 7m) && METEOR_PROFILE=500 meteor npm run test && pkill node

# Generate app bundle
USER root
RUN cd /app/Rocket.Chat && \
    METEOR_PROFILE=500 meteor build --server-only --directory /app \
    && cd /app/bundle/programs/server && npm install

# Final cleanup and ownership adjustments
RUN chown -R rocketchat:rocketchat /app && chmod -R ugo+rwX /app
